export default {
  FETCH_RESTAURANTS_INIT: 'tabb/restaurant/FETCH_RESTAURANTS_INIT',
  FETCH_RESTAURANTS_DONE: 'tabb/restaurant/FETCH_RESTAURANTS_DONE',
  FETCH_RESTAURANTS_FAIL: 'tabb/restaurant/FETCH_RESTAURANTS_FAIL',
  FETCH_STATUS_INIT: 'tabb/restaurant/FETCH_STATUS_INIT',
  FETCH_STATUS_DONE: 'tabb/restaurant/FETCH_STATUS_DONE',
  FETCH_STATUS_FAIL: 'tabb/restaurant/FETCH_STATUS_FAIL',
  CHECKIN_INIT: 'tabb/restaurant/CHECKIN_INIT',
  CHECKIN_DONE: 'tabb/restaurant/CHECKIN_DONE',
  CHECKIN_FAIL: 'tabb/restaurant/CHECKIN_FAIL',
};
