export default {
  FETCH_RESTAURANTS_INIT: 'tabb/user/FETCH_RESTAURANTS_INIT',
  FETCH_RESTAURANTS_DONE: 'tabb/user/FETCH_RESTAURANTS_DONE',
  FETCH_RESTAURANTS_FAIL: 'tabb/user/FETCH_RESTAURANTS_FAIL',
}
