export const FETCH_RESTAURANTINGREDIENTS_INIT = 'dinify/addon/FETCH_RESTAURANTINGREDIENTS_INIT';
export const FETCH_RESTAURANTINGREDIENTS_DONE = 'dinify/addon/FETCH_RESTAURANTINGREDIENTS_DONE';
export const CREATE_INGREDIENT_INIT = 'dinify/ingredient/CREATE_INGREDIENT_INIT';
export const CREATE_INGREDIENT_DONE = 'dinify/ingredient/CREATE_INGREDIENT_DONE';
export const CREATE_INGREDIENT_FAIL = 'dinify/ingredient/CREATE_INGREDIENT_FAIL';
export const REMOVE_INGREDIENT_INIT = 'dinify/ingredient/REMOVE_INGREDIENT_INIT';
export const REMOVE_INGREDIENT_FAIL = 'dinify/ingredient/REMOVE_INGREDIENT_FAIL';
export const UPDATE_INGREDIENT_INIT = 'dinify/ingredient/UPDATE_INGREDIENT_INIT';
