export default {
  LOGIN_INIT: 'tabb/auth/LOGIN_INIT',
  LOGIN_DONE: 'tabb/auth/LOGIN_DONE',
  LOGIN_FAIL: 'tabb/auth/LOGIN_FAIL',
  SIGNUP_INIT: 'tabb/auth/SIGNUP_INIT',
  SIGNUP_DONE: 'tabb/auth/SIGNUP_DONE',
  SIGNUP_FAIL: 'tabb/auth/SIGNUP_FAIL',
  FBAUTH_INIT: 'tabb/auth/FBAUTH_INIT',
  FBAUTH_DONE: 'tabb/auth/FBAUTH_DONE',
  FBAUTH_FAIL: 'tabb/auth/FBAUTH_FAIL',
  GOOGLE_AUTH_INIT: 'tabb/auth/GOOGLE_AUTH_INIT',
  GOOGLE_AUTH_DONE: 'tabb/auth/GOOGLE_AUTH_DONE',
  GOOGLE_AUTH_FAIL: 'tabb/auth/GOOGLE_AUTH_FAIL',
  LOGOUT_INIT: 'tabb/auth/LOGOUT_INIT',
  LOGOUT_DONE: 'tabb/auth/LOGOUT_DONE',
};
