export default {
  FETCH_ME_INIT: 'tabb/user/FETCH_ME_INIT',
  FETCH_ME_DONE: 'tabb/user/FETCH_ME_DONE',
  FETCH_ME_FAIL: 'tabb/user/FETCH_ME_FAIL',
  FETCH_USER_INIT: 'tabb/user/FETCH_USER_INIT',
  FETCH_USER_DONE: 'tabb/user/FETCH_USER_DONE',
  FETCH_USER_FAIL: 'tabb/user/FETCH_USER_FAIL',
  FETCHALL_USER_INIT: 'tabb/user/FETCHALL_USER_INIT',
};
