export default {
  FETCH_BILL_INIT: 'tabb/bill/FETCH_BILL_INIT',
  FETCH_BILL_DONE: 'tabb/bill/FETCH_BILL_DONE',
  FETCH_BILL_FAIL: 'tabb/bill/FETCH_BILL_FAIL',
  SELECT_BILLITEM: 'tabb/bill/SELECT_BILLITEM',
  SET_GRATITUDE: 'tabb/bill/SET_GRATITUDE',
  SPLIT_BILL_INIT: 'tabb/bill/SPLIT_BILL_INIT',
  SPLIT_BILL_DONE: 'tabb/bill/SPLIT_BILL_DONE',
  SPLIT_BILL_FAIL: 'tabb/bill/SPLIT_BILL_FAIL',
  TRANSFER_BILL_INIT: 'tabb/bill/TRANSFER_BILL_INIT',
  TRANSFER_BILL_DONE: 'tabb/bill/TRANSFER_BILL_DONE',
  TRANSFER_BILL_FAIL: 'tabb/bill/TRANSFER_BILL_FAIL',
};
