export default {
  FETCH_BILL_INIT: 'tabb/bill/FETCH_BILL_INIT',
  FETCH_BILL_DONE: 'tabb/bill/FETCH_BILL_DONE',
  FETCH_BILL_FAIL: 'tabb/bill/FETCH_BILL_FAIL',
  SELECT_BILLITEM: 'tabb/bill/SELECT_BILLITEM',
  SET_GRATITUDE: 'tabb/bill/SET_GRATITUDE',
};
