export default {
  FETCH_MENUITEMS_INIT: 'tabb/menuItem/FETCH_MENUITEMS_INIT',
  FETCH_MENUITEMS_DONE: 'tabb/menuItem/FETCH_MENUITEMS_DONE',
  FETCH_MENUITEMS_FAIL: 'tabb/menuItem/FETCH_MENUITEMS_FAIL',
  FETCH_MENUITEM_INIT: 'tabb/menuItem/FETCH_MENUITEM_INIT',
  FETCH_MENUITEM_DONE: 'tabb/menuItem/FETCH_MENUITEM_DONE',
  FETCH_MENUITEM_FAIL: 'tabb/menuItem/FETCH_MENUITEM_FAIL',
  FAV_MENUITEM_INIT: 'tabb/menuItem/FAV_MENUITEM_INIT',
  FAV_MENUITEM_FAIL: 'tabb/menuItem/FAV_MENUITEM_FAIL',
  FAV_MENUITEM_DONE: 'tabb/menuItem/FAV_MENUITEM_DONE',
  EXCLUDE_INGREDIENT: 'tabb/menuItem/EXCLUDE_INGREDIENT',
  INC_ADDON_QTY: 'tabb/menuItem/INC_ADDON_QTY',
  SELECT_CHOICE: 'tabb/menuItem/SELECT_CHOICE'
};
