export default {
  FETCH_MENUITEMS_INIT: 'tabb/menuCategory/FETCH_MENUITEMS_INIT',
  FETCH_MENUITEMS_DONE: 'tabb/menuCategory/FETCH_MENUITEMS_DONE',
  FETCH_MENUITEMS_FAIL: 'tabb/menuCategory/FETCH_MENUITEMS_FAIL',
  FETCH_MENUITEM_INIT: 'tabb/menuCategory/FETCH_MENUITEM_INIT',
  FETCH_MENUITEM_DONE: 'tabb/menuCategory/FETCH_MENUITEM_DONE',
  FETCH_MENUITEM_FAIL: 'tabb/menuCategory/FETCH_MENUITEM_FAIL',
};
