export default {
  ACTIVE_ACTION: 'tabb/ui/ACTIVE',
  UNACTIVE_ACTION: 'tabb/ui/UNACTIVE',
  CONFIRMED_PAYMENT_DONE: 'tabb/ui/CONFIRMED_PAYMENT_DONE',
  CONFIRMED_ORDER_DONE: 'tabb/ui/CONFIRMED_ORDER_DONE'
};
