export default {
  ADD_TO_CART_INIT: 'dinify/cart/ADD_TO_CART_INIT',
  ADD_TO_CART_DONE: 'dinify/cart/ADD_TO_CART_DONE',
  ADD_TO_CART_FAIL: 'dinify/cart/ADD_TO_CART_FAIL',
  REMOVE_ORDERITEM_INIT: 'dinify/cart/REMOVE_ORDERITEM_INIT',
  REMOVE_ORDERITEM_DONE: 'dinify/cart/REMOVE_ORDERITEM_DONE',
  REMOVE_ORDERITEM_FAIL: 'dinify/cart/REMOVE_ORDERITEM_FAIL',
  FETCH_CART_INIT: 'dinify/cart/FETCH_CART_INIT',
  FETCH_CART_DONE: 'dinify/cart/FETCH_CART_DONE',
  FETCH_CART_FAIL: 'dinify/cart/FETCH_CART_FAIL',
  ORDER_INIT: 'dinify/cart/ORDER_INIT',
  ORDER_DONE: 'dinify/cart/ORDER_DONE',
  ORDER_FAIL: 'dinify/cart/ORDER_FAIL',
  SET_ORDERTYPE: 'dinify/cart/SET_ORDERTYPE'
};
