export const REPORT_CAMPAIGN_ACTION_INIT = 'dinify/reporting/REPORT_CAMPAIGN_ACTION_INIT';
export const REPORT_CAMPAIGN_ACTION_DONE = 'dinify/reporting/REPORT_CAMPAIGN_ACTION_DONE';
export const REPORT_CAMPAIGN_ACTION_FAIL = 'dinify/reporting/REPORT_CAMPAIGN_ACTION_FAIL';
