const p = 'dinify/restaurant';

export const BOOTSTRAP = `${p}/BOOTSTRAP`;
export const FETCH_RESTAURANT_INIT = `${p}/FETCH_RESTAURANT_INIT`;
export const FETCH_RESTAURANT_DONE = `${p}/FETCH_RESTAURANT_DONE`;
export const FETCH_MANAGEDRESTAURANTS_INIT = `${p}/FETCH_MANAGEDRESTAURANTS_INIT`;
export const FETCH_MANAGEDRESTAURANTS_DONE = `${p}/FETCH_MANAGEDRESTAURANTS_DONE`;
export const LOAD_RESTAURANT = `${p}/LOAD_RESTAURANT`;
