export const UPDATECUSOMIZATIONS_INIT = 'dinify/menuItem/UPDATECUSOMIZATIONS_INIT';
export const UPDATECUSOMIZATIONS_FAIL = 'dinify/menuItem/UPDATECUSOMIZATIONS_FAIL';
export const UPDATECUSOMIZATIONS_UPDATING = 'dinify/menuItem/UPDATECUSOMIZATIONS_UPDATING';
export const UPDATE_MENUITEM_INIT = 'dinify/menuItem/UPDATE_MENUITEM_INIT';
export const CREATE_MENUITEM_DONE = 'dinify/menuItem/CREATE_MENUITEM_DONE';
export const REMOVE_MENUITEM_INIT = 'dinify/menuItem/REMOVE_MENUITEM_INIT';
export const REMOVE_MENUITEM_FAIL = 'dinify/menuItem/REMOVE_MENUITEM_FAIL';
export const UPDATE_ITEMIMAGE_DONE = 'dinify/menuItem/UPDATE_ITEMIMAGE_DONE';
