export const UPDATECUSOMIZATIONS_INIT = 'dinify/menuItem/UPDATECUSOMIZATIONS_INIT';
export const UPDATECUSOMIZATIONS_FAIL = 'dinify/menuItem/UPDATECUSOMIZATIONS_FAIL';
export const UPDATECUSOMIZATIONS_UPDATING = 'dinify/menuItem/UPDATECUSOMIZATIONS_UPDATING';

export const FETCH_MENUITEM_INIT = 'dinify/menuItem/FETCH_MENUITEM_INIT';
export const FETCH_MENUITEM_DONE = 'dinify/menuItem/FETCH_MENUITEM_DONE';
export const FETCH_MENUITEM_FAIL = 'dinify/menuItem/FETCH_MENUITEM_FAIL';

export const UPDATE_MENUITEM_INIT = 'dinify/menuItem/UPDATE_MENUITEM_INIT';
export const UPDATE_MENUITEM_DONE = 'dinify/menuItem/UPDATE_MENUITEM_DONE';
export const UPDATE_MENUITEM_FAIL = 'dinify/menuItem/UPDATE_MENUITEM_FAIL';

export const CREATE_MENUITEM_INIT = 'dinify/menuItem/CREATE_MENUITEM_INIT';
export const CREATE_MENUITEM_DONE = 'dinify/menuItem/CREATE_MENUITEM_DONE';
export const CREATE_MENUITEM_FAIL = 'dinify/menuItem/CREATE_MENUITEM_FAIL';

export const REMOVE_MENUITEM_INIT = 'dinify/menuItem/REMOVE_MENUITEM_INIT';
export const REMOVE_MENUITEM_DONE = 'dinify/menuItem/REMOVE_MENUITEM_DONE';
export const REMOVE_MENUITEM_FAIL = 'dinify/menuItem/REMOVE_MENUITEM_FAIL';

export const UPDATE_ITEMIMAGE_DONE = 'dinify/menuItem/UPDATE_ITEMIMAGE_DONE';

export const REORDER_MENUITEM_INIT = 'dinify/menuItem/REORDER_MENUITEM_INIT';

export const ASSIGN_INGREDIENT_INIT = 'dinify/menuItem/ASSIGN_INGREDIENT_INIT';
export const ASSIGN_INGREDIENT_DONE = 'dinify/menuItem/ASSIGN_INGREDIENT_DONE';
export const ASSIGN_INGREDIENT_FAIL = 'dinify/menuItem/ASSIGN_INGREDIENT_FAIL';

export const UNASSIGN_INGREDIENT_INIT = 'dinify/menuItem/UNASSIGN_INGREDIENT_INIT';
export const UNASSIGN_INGREDIENT_DONE = 'dinify/menuItem/UNASSIGN_INGREDIENT_DONE';
export const UNASSIGN_INGREDIENT_FAIL = 'dinify/menuItem/UNASSIGN_INGREDIENT_FAIL';

export const SET_INGREDIENT_EXCLUDABILITY_INIT = 'dinify/menuItem/SET_INGREDIENT_EXCLUDABILITY_INIT';
export const SET_INGREDIENT_EXCLUDABILITY_DONE = 'dinify/menuItem/SET_INGREDIENT_EXCLUDABILITY_DONE';
export const SET_INGREDIENT_EXCLUDABILITY_FAIL = 'dinify/menuItem/SET_INGREDIENT_EXCLUDABILITY_FAIL';

export const ASSIGN_ADDON_INIT = 'dinify/menuItem/ASSIGN_ADDON_INIT';
export const ASSIGN_ADDON_DONE = 'dinify/menuItem/ASSIGN_ADDON_DONE';
export const ASSIGN_ADDON_FAIL = 'dinify/menuItem/ASSIGN_ADDON_FAIL';

export const UNASSIGN_ADDON_INIT = 'dinify/menuItem/UNASSIGN_ADDON_INIT';
export const UNASSIGN_ADDON_DONE = 'dinify/menuItem/UNASSIGN_ADDON_DONE';
export const UNASSIGN_ADDON_FAIL = 'dinify/menuItem/UNASSIGN_ADDON_FAIL';
