export const FETCH_MENUCATEGORIES_INIT = 'dinify/menuCategory/FETCH_MENUCATEGORIES_INIT';
export const FETCH_MENUCATEGORIES_DONE = 'dinify/menuCategory/FETCH_MENUCATEGORIES_DONE';
export const FETCH_MENUCATEGORIES_FAIL = 'dinify/menuCategory/FETCH_MENUCATEGORIES_FAIL';
