const p = 'dinify/restaurant';

export const FETCH_RESTAURANT_INIT = `${p}/FETCH_RESTAURANT_INIT`;
export const FETCH_RESTAURANT_DONE = `${p}/FETCH_RESTAURANT_DONE`;
export const FETCH_RESTAURANTWAITERBOARDS_INIT = `${p}/FETCH_RESTAURANTWAITERBOARDS_INIT`;
export const FETCH_RESTAURANTWAITERBOARDS_DONE = `${p}/FETCH_RESTAURANTWAITERBOARDS_DONE`;
export const SEND_PUBLISHREQUEST_INIT = `${p}/SEND_PUBLISHREQUEST_INIT`;
export const SEND_PUBLISHREQUEST_DONE = `${p}/SEND_PUBLISHREQUEST_DONE`;
export const SEND_PUBLISHREQUEST_FAIL = `${p}/SEND_PUBLISHREQUEST_FAIL`;

