
export const FETCH_MENUITEM_INIT = 'd/mI/FETCH_MENUITEM_INIT';
export const FETCH_MENUITEM_DONE = 'd/mI/FETCH_MENUITEM_DONE';
export const FETCH_MENUITEM_FAIL = 'd/mI/FETCH_MENUITEM_FAIL';

export const UPDATE_MENUITEM_INIT = 'd/mI/UPDATE_MENUITEM_INIT';
export const UPDATE_MENUITEM_DONE = 'd/mI/UPDATE_MENUITEM_DONE';
export const UPDATE_MENUITEM_FAIL = 'd/mI/UPDATE_MENUITEM_FAIL';

export const CREATE_MENUITEM_INIT = 'd/mI/CREATE_MENUITEM_INIT';
export const CREATE_MENUITEM_DONE = 'd/mI/CREATE_MENUITEM_DONE';
export const CREATE_MENUITEM_FAIL = 'd/mI/CREATE_MENUITEM_FAIL';

export const REMOVE_MENUITEM_INIT = 'd/mI/REMOVE_MENUITEM_INIT';
export const REMOVE_MENUITEM_DONE = 'd/mI/REMOVE_MENUITEM_DONE';
export const REMOVE_MENUITEM_FAIL = 'd/mI/REMOVE_MENUITEM_FAIL';

export const UPDATE_ITEMIMAGE_INIT = 'd/mI/UPDATE_ITEMIMAGE_INIT';
export const UPDATE_ITEMIMAGE_DONE = 'd/mI/UPDATE_ITEMIMAGE_DONE';

export const REORDER_MENUITEM_INIT = 'd/mI/REORDER_MENUITEM_INIT';

export const ASSIGN_INGREDIENT_INIT = 'd/mI/ASSIGN_INGREDIENT_INIT';
export const ASSIGN_INGREDIENT_DONE = 'd/mI/ASSIGN_INGREDIENT_DONE';
export const ASSIGN_INGREDIENT_FAIL = 'd/mI/ASSIGN_INGREDIENT_FAIL';

export const UNASSIGN_INGREDIENT_INIT = 'd/mI/UNASSIGN_INGREDIENT_INIT';
export const UNASSIGN_INGREDIENT_DONE = 'd/mI/UNASSIGN_INGREDIENT_DONE';
export const UNASSIGN_INGREDIENT_FAIL = 'd/mI/UNASSIGN_INGREDIENT_FAIL';

export const SET_INGREDIENT_EXCLUDABILITY_INIT = 'd/mI/SET_INGREDIENT_EXCLUDABILITY_INIT';
export const SET_INGREDIENT_EXCLUDABILITY_DONE = 'd/mI/SET_INGREDIENT_EXCLUDABILITY_DONE';
export const SET_INGREDIENT_EXCLUDABILITY_FAIL = 'd/mI/SET_INGREDIENT_EXCLUDABILITY_FAIL';

export const ASSIGN_ADDON_INIT = 'd/mI/ASSIGN_ADDON_INIT';
export const ASSIGN_ADDON_DONE = 'd/mI/ASSIGN_ADDON_DONE';
export const ASSIGN_ADDON_FAIL = 'd/mI/ASSIGN_ADDON_FAIL';

export const UNASSIGN_ADDON_INIT = 'd/mI/UNASSIGN_ADDON_INIT';
export const UNASSIGN_ADDON_DONE = 'd/mI/UNASSIGN_ADDON_DONE';
export const UNASSIGN_ADDON_FAIL = 'd/mI/UNASSIGN_ADDON_FAIL';

export const ASSIGN_OPTION_INIT = 'd/mI/ASSIGN_OPTION_INIT';
export const ASSIGN_OPTION_DONE = 'd/mI/ASSIGN_OPTION_DONE';
export const ASSIGN_OPTION_FAIL = 'd/mI/ASSIGN_OPTION_FAIL';

export const UNASSIGN_OPTION_INIT = 'd/mI/UNASSIGN_OPTION_INIT';
export const UNASSIGN_OPTION_DONE = 'd/mI/UNASSIGN_OPTION_DONE';
export const UNASSIGN_OPTION_FAIL = 'd/mI/UNASSIGN_OPTION_FAIL';
