
export const UPDATE_ITEMIMAGE_INIT = 'd/mI/UPDATE_ITEMIMAGE_INIT';
export const UPDATE_ITEMIMAGE_DONE = 'd/mI/UPDATE_ITEMIMAGE_DONE';

export const REORDER_MENUITEM_INIT = 'd/mI/REORDER_MENUITEM_INIT';
