export default {
  FETCH_MENUCATEGORIES_INIT: 'tabb/menuCategory/FETCH_MENUCATEGORIES_INIT',
  FETCH_MENUCATEGORIES_DONE: 'tabb/menuCategory/FETCH_MENUCATEGORIES_DONE',
  FETCH_MENUCATEGORIES_FAIL: 'tabb/menuCategory/FETCH_MENUCATEGORIES_FAIL',
};
