export default {
  FETCH_SEATS_INIT: 'tabb/seat/FETCH_SEATS_INIT',
  FETCH_SEATS_DONE: 'tabb/seat/FETCH_SEATS_DONE',
  FETCH_SEATS_FAIL: 'tabb/seat/FETCH_SEATS_FAIL',
  SELECT_BILLITEM: 'tabb/seat/SELECT_BILLITEM',
  SELECT_SEAT: 'tabb/seat/SELECT_SEAT',
  CLEAR_SELECTED_BILLITEMS: 'tabb/seat/CLEAR_SELECTED_BILLITEMS'
};
