export default {
  LOGIN_INIT: 'dinify/auth/LOGIN_INIT',
  LOGIN_DONE: 'dinify/auth/LOGIN_DONE',
  LOGIN_FAIL: 'dinify/auth/LOGIN_FAIL',
  SIGNUP_INIT: 'dinify/auth/SIGNUP_INIT',
  SIGNUP_DONE: 'dinify/auth/SIGNUP_DONE',
  SIGNUP_FAIL: 'dinify/auth/SIGNUP_FAIL',
  FBAUTH_INIT: 'dinify/auth/FBAUTH_INIT',
  FBAUTH_DONE: 'dinify/auth/FBAUTH_DONE',
  FBAUTH_FAIL: 'dinify/auth/FBAUTH_FAIL',
  GOOGLE_AUTH_INIT: 'dinify/auth/GOOGLE_AUTH_INIT',
  GOOGLE_AUTH_DONE: 'dinify/auth/GOOGLE_AUTH_DONE',
  GOOGLE_AUTH_FAIL: 'dinify/auth/GOOGLE_AUTH_FAIL',
  LOGOUT_INIT: 'dinify/auth/LOGOUT_INIT',
  LOGOUT_DONE: 'dinify/auth/LOGOUT_DONE',
  SET_PAGE: 'dinify/auth/SET_PAGE',
  SET_SHOWPASSWORD: 'dinify/auth/SET_SHOWPASSWORD',
  SET_LINKPROVIDERS: 'dinify/auth/SET_LINKPROVIDERS',
};
