export const FETCH_RESTAURANT_INIT = 'dinify/restaurant/FETCH_RESTAURANT_INIT';
export const FETCH_RESTAURANT_DONE = 'dinify/restaurant/FETCH_RESTAURANT_DONE';
export const FETCH_RESTAURANTWAITERBOARDS_INIT = 'dinify/restaurant/FETCH_RESTAURANTWAITERBOARDS_INIT';
export const FETCH_RESTAURANTWAITERBOARDS_DONE = 'dinify/restaurant/FETCH_RESTAURANTWAITERBOARDS_DONE';
