const p = 'dinify/restaurant';

export const FETCH_RESTAURANTS_INIT = `${p}/FETCH_RESTAURANTS_INIT`;
export const FETCH_RESTAURANTS_DONE = `${p}/FETCH_RESTAURANTS_DONE`;
export const FETCH_RESTAURANTS_FAIL = `${p}/FETCH_RESTAURANTS_FAIL`;
export const FETCH_RESTAURANT_INIT = `${p}/FETCH_RESTAURANT_INIT`;
export const FETCH_RESTAURANT_DONE = `${p}/FETCH_RESTAURANT_DONE`;
export const FETCH_RESTAURANT_FAIL = `${p}/FETCH_RESTAURANT_FAIL`;
export const FETCH_STATUS_INIT = `${p}/FETCH_STATUS_INIT`;
export const FETCH_STATUS_DONE = `${p}/FETCH_STATUS_DONE`;
export const FETCH_STATUS_FAIL = `${p}/FETCH_STATUS_FAIL`;
export const CHECKIN_INIT = `${p}/CHECKIN_INIT`;
export const CHECKIN_DONE = `${p}/CHECKIN_DONE`;
export const CHECKIN_FAIL = `${p}/CHECKIN_FAIL`;
export const FAV_RESTAURANT_INIT = `${p}/FAV_RESTAURANT_INIT`;
export const FAV_RESTAURANT_FAIL = `${p}/FAV_RESTAURANT_FAIL`;
export const FAV_RESTAURANT_DONE = `${p}/FAV_RESTAURANT_DONE`;
