export default {
  FETCH_MENUCATEGORIES_INIT: 'dinify/menuCategory/FETCH_MENUCATEGORIES_INIT',
  FETCH_MENUCATEGORIES_DONE: 'dinify/menuCategory/FETCH_MENUCATEGORIES_DONE',
  FETCH_MENUCATEGORIES_FAIL: 'dinify/menuCategory/FETCH_MENUCATEGORIES_FAIL',
};
